

mybatis:
  mapper-locations: classpath:mybatis/*.xml

server:
  port: 8080

spring:
  datasource:
    password: FAST707e
    url: jdbc:mysql://rm-bp12g7e0k6w828uc6bo.mysql.rds.aliyuncs.com:3306/final?serverTimezone=GMT%2B8
    username: kaze
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false

  redis:
    host: 182.92.185.137
    password: 423414a.
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher