mybatis:
  mapper-locations: classpath:com/geekgame/demo/dao/*.xml

server:
  port: 8082

spring:
  datasource:
    password: ZABzueZ3
    url: jdbc:mysql://sh-cynosdbmysql-grp-knpl8owi.sql.tencentcdb.com:21104/springboot_demo?serverTimezone=GMT%2B8
    username: root

  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false

  redis:
    host: 182.92.185.137
    password: 423414a.
    port: 6379
